// <auto-generated />
namespace DeviceReg.Common.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserDeviceRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDeviceRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061021109_UserDeviceRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
